<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Kannapi" name="com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest" tests="5" failures="3" timestamp="06 Feb 2023 19:26:23 GMT" time="21.856" errors="0">
  <testcase name="verifyLogin" time="5.735" classname="com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest"/>
  <testcase name="verifyLogin" time="4.039" classname="com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Login failed,Invalid username and password expected [Dashboard | 7rmart supermarket] but found [Login | 7rmart supermarket]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Login failed,Invalid username and password expected [Dashboard | 7rmart supermarket] but found [Login | 7rmart supermarket]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at pages.LoginPageWithDataprovider.loginToApp(LoginPageWithDataprovider.java:40)
	at com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest.verifyLogin(LoginPageWithDataproviderTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase name="verifyLogin" time="3.511" classname="com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Login failed,Invalid username and password expected [Dashboard | 7rmart supermarket] but found [Login | 7rmart supermarket]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Login failed,Invalid username and password expected [Dashboard | 7rmart supermarket] but found [Login | 7rmart supermarket]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at pages.LoginPageWithDataprovider.loginToApp(LoginPageWithDataprovider.java:40)
	at com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest.verifyLogin(LoginPageWithDataproviderTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase name="verifyLogin" time="3.475" classname="com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Login failed,Invalid username and password expected [Dashboard | 7rmart supermarket] but found [Login | 7rmart supermarket]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Login failed,Invalid username and password expected [Dashboard | 7rmart supermarket] but found [Login | 7rmart supermarket]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at pages.LoginPageWithDataprovider.loginToApp(LoginPageWithDataprovider.java:40)
	at com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest.verifyLogin(LoginPageWithDataproviderTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase name="verifyLogin" time="5.096" classname="com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest"/>
</testsuite> <!-- com.obsqura.selenium.FinalProject.LoginPageWithDataproviderTest -->
